<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Verdant.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.2.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="TIKSN-Framework" Version="5.5.0" />
  </ItemGroup>

</Project>
