<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Verdant.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ardalis.Specification" Version="9.3.1" />
    <PackageReference Include="Autofac" Version="9.3.0" />
    <PackageReference Include="MediatR" Version="14.2.0" />
    <PackageReference Include="TIKSN-Framework" Version="5.7.2" />
  </ItemGroup>

</Project>
